# List of playbooks to include on the Playbooks page in additon to the
# FICAM-produced playbooks located in the /_playbooks/ and PDF versions in /assets/playbooks folder.
# Newest on top

- title: Enterprise Single Sign-On Playbook
  type: PDF
  pubdate: 02/021
  description: The Enterprise SSO Playbook is a five-step playbook to aid agenices in planning an SSO or Identity Federation service 
  url: /docs/playbook-sso.pdf
  

- title: Digital Worker Identity Playbook
  type: PDF
  pubdate: 01/2021
  description: The Digital Worker Identity Playbook is a practical guide to manage digital worker identities.
  url: /docs/playbook-digital-worker.pdf
  
- title: Digital Identity Risk Assessment Playbook
  type: PDF
  pubdate: 09/2020
  description: The Digital Identity Risk Assessment playbook is a six-step playbook to complete a digital identity risk assessment as described in OMB Memo 19-17 and NIST Special Publication 800-63-3.
  url: /docs/playbook-dira.pdf
  
- title: Federal Identity, Credential, and Access Management Roadmap Version 2.0
  type: PDF
  pubdate: 12/2011
  description: The FICAM Roadmap, developed by working groups under the Federal CIO Council, contains processes, procedures, and considerations for planning and managing logical access, physical access, enterprise identity management, and federation within federal agencies. (Note, the enterprise architecture section of the Roadmap has been superceded by the FICAM Architecture Playbook.)
  url: /docs/roadmap-ficam.pdf
